name: ci

on: [push]

jobs:
  lints:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: 1.85
          components: rustfmt
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: false
      - run: just lints

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@nightly
        with:
          toolchain: 1.85
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: false
      - run: just lint-native

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85
      - uses: taiki-e/install-action@nextest
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: true
      - run: just test

  dry-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/install-action@just
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85
      - uses: katyo/publish-crates@v2
        with:
            dry-run: true
            check-repo: ${{ github.event_name == 'push' }}
