name: Release version

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Just
        uses: taiki-e/install-action@just

      - name: Installs stable rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.85

      - uses: katyo/publish-crates@v2
        with:
            registry-token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
